### ISSUE TITLE
missing whitespace between code and agile comment

### ISSUE THREAD

**Issue by biancode** [AgileReview-Project/AgileReview-EclipsePlugin#2]
Hi AgileReview-Team,

thanks for the AgileReview tool!
We tested with version 0.9.1 and there is a tiny problem. The comment from AgileReview does attaching without a whitespace between the source code and the comment. That is a problem for the parser of our programming language. Please, could you fix that? It is not to configure - ' /*' becomes '/*' while attaching.

kind regards
Klaus

**Comment by postmann** [comment]
This issue was moved to AgileReview-Project/AgileReview-Legacy-Plugin#22

**Comment by biancode** [comment]
it works very well - thank you
