### ISSUE TITLE
Preview Description in Comments Summary

### ISSUE THREAD

**Issue by StefanMacke** [AgileReview-Project/AgileReview-EclipsePlugin#3]
Is it possible to preview the Description for each comment as a column in the "Comments Summary" view? That would make it easier to find the interesting comments and grouping similar comments would also be possible.

![commentssummary](https://user-images.githubusercontent.com/424316/33996517-b99984ae-e0e1-11e7-8688-c33dfe3ebf95.jpg)

However, thank you for your work on the AgileReview plugin!

**Comment by postmann** [comment]
This issue was moved to AgileReview-Project/AgileReview-Legacy-Plugin#21
