### ISSUE TITLE
Review Details and Comment Details in different views

### ISSUE THREAD

**Issue by ghost** [AgileReview-Project/AgileReview-EclipsePlugin#4]
Is it possible to show the Review Details and Comment Details in different views so that it is shown at the same time? At the moment the Review Details and Comment Details are shown in the same view by clicking on a review or comment.

Thank you, regards

**Comment by maybeec** [comment]
Hi, no this is not possible currently. We decided to have both detail views in one to not overload the user with multple views to be managed.

**Comment by biancode** [comment]
Hi Malte,

I'm sorry, but it's not easy to work with this changing view when you're mainly using the keyboard.

cya
Klaus

**Comment by maybeec** [comment]
Thanks for the Feedback @biancode .
Can you scatch two to three workflows you would like to navigate through with the keyboard?
Maybe we can adress it, if we get to know what your common navigation is about.

**Comment by biancode** [comment]
Yes, we could do that. Another problem is our Eclipse - NaturalOne (SAG). It includes some Plugins, which catches the focus and so everytime we switch to the Review Explorer View. That brings the comment  detail view back to the review detail view. That problem will occure with every PlugIn, which sets the focus to the Workbench of Eclipse.

**Comment by maybeec** [comment]
Ok, so by having two seperate views, we would get rid of the unintended switching between the views. Makes. sense.

**Comment by biancode** [comment]
Xtext and LaTeX should get the same trouble, because they compile every change/save too and that brings the console view of Eclipse in front and boom - focus is lost and views will change from comment to review

**Comment by maybeec** [comment]
You are right, I created a new issue in the right repository. Lets continue tracking and further discussion there.

AgileReview-Project/AgileReview-Legacy-Plugin#23

**Comment by biancode** [comment]
Thank you very much!
